server:
  port: 8084
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cart-service-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/online-market-buyers
keycloak:
  realms:
    uri:
      buyers: http://localhost:8082/realms/online-market-buyers
      sellers: http://localhost:8082/realms/online-market-sellers
media:
  storage:
    location: C:\Users\никита\Desktop\Online_Market_Pet_Project\comments-and-shopping-cart-service\src\main\resources\static\uploads