market:
  services:
    products:
      uri: http://localhost:8081
      registration-id: keycloak
    review-api: http://localhost:8084
    orders-and-notification:
      uri: http://localhost:8087
spring:
  security:
    oauth2:
        client:
          provider:
            keycloak:
              issuer-uri: http://localhost:8082/realms/online-market-sellers
              user-name-attribute: preferred_username
          registration:
            keycloak:
              provider: keycloak
              client-id: sellers-app
              client-secret: Ja89I0aHVgz5rJ9JoSjneoQLxc9tNFBI
              scope:
                - openid
                - view_products
                - edit_products
                - microprofile-jwt
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
