
market:
  services:
    products:
      uri: http://localhost:8081
      registrationId: keycloak
    products-from-cart:
      uri: http://localhost:8084
      registrationId: keycloak
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/online-market-buyers
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: buyers-app
            client-secret: Un8PgJEmIsN748AT3OP3F8qjvmrD2Sxp
            scope:
              - openid
              - view_products
              - microprofile-jwt
server:
  port: 8083
