create schema if not exists products_schema;

create table products_schema.t_product(
    id int primary key generated by default as identity,
    c_title varchar(100) not null check ( bit_length(trim(c_title)) >= 3),
    c_details varchar(1000) not null check ( bit_length(c_details) > 5 )
);