create table products_schema.t_product_media
(
    id int primary key generated by default as identity ,
    c_product_id int references products_schema.t_product(id) on delete cascade ,
    c_media_path varchar,
    c_media_type varchar
);