ALTER TABLE products_schema.t_product DROP COLUMN seller_subject;

create table products_schema.t_seller(
        id int primary key generated by default as identity ,
        c_preferred_username varchar,
        c_email varchar,
        c_subject varchar
);

ALTER table products_schema.t_product add column c_seller int references products_schema.t_seller(id) on delete cascade