server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: nikita2005
    url: jdbc:postgresql://localhost:5432/products
  flyway:
    schemas:
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/online-market-sellers
keycloak:
  realms:
    uri:
      buyers: http://localhost:8082/realms/online-market-buyers
      sellers: http://localhost:8082/realms/online-market-sellers
