server:
  port: 8081
spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/online-market-sellers
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
keycloak:
  realms:
    uri:
      buyers: http://localhost:8082/realms/online-market-buyers
      sellers: http://localhost:8082/realms/online-market-sellers
media:
  storage:
    location: C:\Users\никита\Desktop\Online_Market_Pet_Project\products-service\src\main\resources\static\uploads
