create table t_order(
    id int primary key generated by default as identity,
    c_time_of_created TIMESTAMP,
    c_product_id int not null,
    c_product_title varchar(100) not null,
    c_count int check ( c_count >= 1 ),
    c_seller_username varchar not null,
    c_seller_email varchar not null,
    c_buyer_username varchar not null,
    c_buyer_email varchar not null,
    c_buyer_detail varchar not null,
    c_address varchar not null,
    c_postcode varchar not null,
    c_amount NUMERIC(10,2) NOT NULL,
    с_payment_type varchar not null
);

